# Generated by Django 3.0.7 on 2020-06-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('sku_number', models.IntegerField()),
                ('qty_in_stock', models.IntegerField()),
            ],
        ),
    ]
