# Generated by Django 3.0.8 on 2020-07-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20200703_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
