# Generated by Django 3.0.8 on 2020-07-24 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20200724_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billing',
            name='zip',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='billing',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='ecommerce.Billing'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='shipping',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='ecommerce.Shipping'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
