# Generated by Django 3.0.8 on 2020-07-24 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_auto_20200724_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcartthroughmodel',
            name='cart',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cart_products',
                to='ecommerce.Cart'),
        ),
        migrations.AlterField(
            model_name='productcartthroughmodel',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cart_products',
                to='ecommerce.Product'),
        ),
        migrations.AlterField(
            model_name='productpurchasethroughmodel',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='purchase_products',
                to='ecommerce.Product'),
        ),
        migrations.AlterField(
            model_name='productpurchasethroughmodel',
            name='purchase',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='purchase_products',
                to='ecommerce.Purchase'),
        ),
    ]
