# Generated by Django 3.0.8 on 2020-07-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20200724_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='name',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
