# Generated by Django 3.0.8 on 2020-08-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_billing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='phone',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='phone',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
