# Generated by Django 3.0.8 on 2020-08-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_auto_20200808_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
